---
deployment:
  tasks:
    - echo "--- Dashboard Deployment Started ---" > deploy.log
    - /opt/cpanel/ea-nodejs20/bin/npm install >> deploy.log 2>&1
    - /opt/cpanel/ea-nodejs20/bin/npm run build >> deploy.log 2>&1
    - /bin/cp -R build/client/* /home/futurebd/manageportal.futuretechaddis.com/ >> deploy.log 2>&1
    - echo "--- Dashboard Deployment Finished ---" >> deploy.log
