---
deployment:
  tasks:
    - /opt/cpanel/ea-nodejs20/bin/npm install
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - /bin/cp -R build/client/* /home/futurebd/manageportal.futuretechaddis.com/
