---
deployment:
  tasks:
    - echo "--- Dashboard Deployment Started ---" > deploy.log
    - export PATH=$PATH:/opt/alt/alt-nodejs20/root/usr/bin:/opt/cpanel/ea-nodejs20/bin
    - NPM_PATH=$(which npm)
    - echo "Detected npm at: $NPM_PATH" >> deploy.log
    - $NPM_PATH install >> deploy.log 2>&1
    - $NPM_PATH run build >> deploy.log 2>&1
    - /bin/cp -R build/client/* /home/futurebd/manageportal.futuretechaddis.com/ >> deploy.log 2>&1
    - echo "--- Dashboard Deployment Finished ---" >> deploy.log
